name: release

on:
  push:
    tags:
      - v*

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v4
      - name: deploy prod
        run: echo deploy prod!
